# -*- coding: utf-8 -*-
"""exercise1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16eZ65Y2bjb8QtmDuszl3QQQHoePa7GWc
"""

def precision(tp, fp, fn):
  return tp / (tp + fp)
def recall(tp, fp, fn):
  return tp / (tp + fn)
def F1_score(tp, fp, fn):
  x1 = precision(tp, fp, fn)
  x2 = recall(tp, fp, fn)
  return 2 * x1 * x2 / (x1 + x2)
def exercise1(tp, fp, fn):
  if(type(tp) != int):
      print("tp must be int")
      return
  elif(type(fp) != int):
      print("fp must be int")
      return
  elif(type(fn) != int):
      print("fn must be int")
  elif(tp <= 0 or fp <= 0 or fn <= 0):
      print("tp and fp and fn must be greater than zero")
      return
  else:
    print(f">> precision is {precision(tp, fp, fn)} \n recall is {recall(tp,fp,fn)} \n f1-score is {F1_score(tp, fp, fn)}")

print ( round ( F1_score ( tp =2 , fp =4 , fn =5) , 2) )

