# -*- coding: utf-8 -*-
"""exercise5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k2p5McxtvTiM-OewD0JnDO4tD1NWMDJi
"""

def md_nre_single_sample (y, y_hat, n, p):
  return (y ** (1 / n) - y_hat ** (1 / n)) ** p

md_nre_single_sample ( y =20 , y_hat =19.5 , n =2 , p =1)