# -*- coding: utf-8 -*-
"""Queue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ajLskI5NuIh6InWesISaaEyqboL6pDYI
"""

class MyQueue:
  def __init__(self, capacity):
    self.capacity = capacity
    self.__queue = []
  def is_empty(self):
    return len(self.__queue) == 0
  def is_full(self):
    return len(self.__queue) == self.capacity
  def dequeue(self):
    return self.__queue.pop(0)
  def enqueue(self, item):
    if not self.is_full():
      self.__queue.append(item)
  def front(self):
    return self.__queue[0]

queue1 = MyQueue ( capacity =5)
queue1 . enqueue (1)

queue1 . enqueue (2)

print ( queue1 . is_full () )


print ( queue1 . front () )


print ( queue1 . dequeue () )

print ( queue1 . front () )


print ( queue1 . dequeue () )


print ( queue1 . is_empty () )

