# -*- coding: utf-8 -*-
"""Stack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ajLskI5NuIh6InWesISaaEyqboL6pDYI
"""

class MyStack:
  def __init__(self, capacity):
    self.capacity = capacity
    self.__stack = []
  def is_empty(self):
    return len(self.__stack) == 0
  def is_full(self):
    return len(self.__stack) == self.capacity
  def pop(self):
    if self.is_empty():
      raise Exception("Stack is empty")
    return self.__stack.pop()
  def push(self, item):
    if self.is_full():
      raise Exception("Stack is full")
    self.__stack.append(item)
  def top(self):
    return self.__stack[-1]

stack1 = MyStack ( capacity =5)

stack1 . push (1)

stack1 . push (2)

print ( stack1 . is_full () )

print ( stack1 . top () )


print ( stack1 . pop () )
print ( stack1 . top () )

print ( stack1 . pop () )
print ( stack1 . is_empty () )

